name: My Workflow
on:
  pull_request:
    branches:
      - development

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release Notes File
        run: |
          # Create or update the release notes file
          echo "test" >> releasenotes.md

      - name: Commit Release Notes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout development
          git add releasenotes.md
          git commit -m "Add release notes"
          git push
